apiVersion: v1
kind: ConfigMap
metadata:
  name: test-file
data:
  data.csv: |
    name,age,email,password
    naka,1,hoge@test.com,jsjos
    tanaka,tanake@test.com,joaoga

--- #ここで区切ることで複数のオブジェクトを記述することができる
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  restartPolicy: Never
  containers:
    - name: busybox
      image: k8s.gcr.io/busybox
      command: ["sleep", "3600"]
      volumeMounts:
        - name: config
          mountPath: "/datadir"
          readOnly: true
  volumes:
    - name: config
      configMap:
        name: test-file
